[package]
name = "Rust-Engine"
version = "0.1.0"
authors = ["tniyer2 <tanishqiyer88@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "Rust-Engine"
path = "main.rs"
